name: funspot
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Barlow
      fonts:
        - asset: assets/fonts/Barlow-Regular.ttf
        - asset: assets/fonts/Barlow-Italic.ttf
          style: italic
        - asset: assets/fonts/Barlow-Medium.ttf
          weight: 600
        - asset: assets/fonts/Barlow-MediumItalic.ttf
          weight: 600
        - asset: assets/fonts/Barlow-Light.ttf
          weight: 500
        - asset: assets/fonts/Barlow-SemiBold.ttf
          weight: 700
